[versions]
minecraft = "26.1.2"

mod_publish_plugin = "2.2.0"

fabric_loom = "1.18.1"
fabric_loader = "0.19.5"
moddevgradle = "2.0.147"
neoforge = "26.1.2.109"

fabric_api = "0.155.3+26.1.2"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }

fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }

# If you have multiple similar dependencies, you can declare a dependency bundle and reference it on the build script with "libs.bundles.example".
[bundles]

[plugins]
mod_publish_plugin = { id = "me.modmuss50.mod-publish-plugin", version.ref = "mod_publish_plugin" }
fabric_loom = { id = "net.fabricmc.fabric-loom", version.ref = "fabric_loom" }
moddevgradle = { id = "net.neoforged.moddev", version.ref = "moddevgradle" }
